# This is a basic workflow to help you get started with Actions

name: release

on:
  issue_comment:
    types: created

jobs:
  append_changelog:
    if: startsWith(github.event.comment.body, '/version')
    env:
      comment: ${{ toJson(github.event.comment) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@0.9.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log(context.payload)
